# Generated by Django 4.2.4 on 2023-08-15 09:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
            },
        ),
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="ID телеграм"),
                ),
            ],
            options={
                "verbose_name": "консультант",
                "verbose_name_plural": "консультанты",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.IntegerField(
                        choices=[
                            (1, "Topic 1"),
                            (2, "Topic 2"),
                            (3, "Topic 3"),
                            (4, "Topic 4"),
                        ]
                    ),
                ),
                ("text", models.TextField()),
                ("result", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultation.consultant",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
    ]
